### ISSUE TITLE
trickster never cache hit

### ISSUE THREAD

**Issue by Wing924** [Comcast/trickster#218]
## bug summary

The trickster always report cache miss, won't report cache hit from metrics.
The response won't be faster when do same query.

## versions

* trickster v1.0-beta4
  * check backend with memory and filesystem
* trickster v1.0-beta3
  * check backend with memory

## configuration

system design
```
trickster --> promxy -+--> prometheus 1
                      |
                      +--> prometheus 2
```

trickster config:
```toml
[main]
instance_id = 1

[proxy_server]
listen_port = 8000

[caches]
  [caches.default]
  type = 'filesystem'
  compression = true

    [caches.default.index]
    reap_interval_secs = 3
    flush_interval_secs = 5
    max_size_bytes = 536870912
    max_size_backoff_bytes = 16777216
    max_size_objects = 0
    max_size_backoff_objects = 100

    [caches.default.filesystem]
    cache_path = '/cache'

[origins]
  [origins.default]
  type = 'prometheus'
  scheme = 'http'
  host = 'promxy:8082'
  cache_name = 'default'
  timeout_secs = 30

[metrics]
listen_port = 8001

[logging]
log_level = 'debug'
```

## reporduce

```bash
time wget -q -O /dev/null http://trickster:8000/api/v1/query_range?query=scrape_samples_scraped&start=1556258146.949&end=1556261746.949&step=14
time wget -q -O /dev/null http://trickster:8000/api/v1/query_range?query=scrape_samples_scraped&start=1556258146.949&end=1556261746.949&step=14
time wget -q -O /dev/null http://trickster:8000/api/v1/query_range?query=scrape_samples_scraped&start=1556258146.949&end=1556261746.949&step=14
# check used time
```

**Comment by jranson** [comment]
Hi Wei - I am currently unable to reproduce this. The URL you provided to reproduce will not work because it includes ampersands, but is not enclosed with quotes. Any command line argument with ampersands _must_ be enclosed with quotation marks or you will get unexpected results. This is not a Trickster thing, it is just how the Linux command line works. When you don't include the quotes, the URL parameters will be forked to their own processes, set ephemeral environment variables and quickly exit, while the main URL will be requested but will return an error due to the missing/forked parameters. So naturally, each time you run this, it will be a cache miss due to the upstream Prom error. To verify this behavior, remove the stdout redirect to /dev/null and look at the Prom output.

I have crafted a sample command that you can use to more reliably run your test. It will request the last 1 hour of data every time you run it. You should get a cache hit on subsequent runs if you are still in the same 14-second step, and a partial cache hit when the step rolls over.

```
THOST="127.0.0.1:9091" && STIME=$(expr $(date +%s) - 3600).000  ETIME=$(date +%s).000 && curl "http://${THOST}/api/v1/query_range?query=scrape_samples_scraped&start=${STIME}&end=${ETIME}&step=14"
```

While running this, you can look @ the metrics page to confirm the cache hit is incrementing. This is best done in an isolated environment where you can directly monitor the metrics.

When I perform this test from a freshly started trickster with no other traffic, here are my results:

On the first call (cache miss), the following relevant metrics increment:
```
trickster_cache_operation_objects_total{cache_name="default",cache_type="memory",operation="get",status="miss"} 1
trickster_proxy_requests_total{cache_status="kmiss",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range"} 1
```

On the second call (waited 15s to register partial cache hit):
```
trickster_cache_operation_objects_total{cache_name="default",cache_type="memory",operation="get",status="hit"} 1
trickster_cache_operation_objects_total{cache_name="default",cache_type="memory",operation="get",status="miss"} 1
trickster_proxy_requests_total{cache_status="kmiss",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range"} 1
trickster_proxy_requests_total{cache_status="phit",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range"} 1
```

On the third call (waited 1s to register full cache hit):
```
trickster_cache_operation_objects_total{cache_name="default",cache_type="memory",operation="get",status="hit"} 2
trickster_cache_operation_objects_total{cache_name="default",cache_type="memory",operation="get",status="miss"} 1
trickster_proxy_requests_total{cache_status="hit",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range"} 1
trickster_proxy_requests_total{cache_status="kmiss",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range"} 1
trickster_proxy_requests_total{cache_status="phit",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range"} 1
```

**Comment by Wing924** [comment]
I write a POC code here:

docker-compose.yml
```yml
version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.9.2
    ports:
    - 9090:9090
  trickster:
    image: tricksterio/trickster:1.0-beta5
    ports:
    - 8000:8000
    - 8001:8001
    volumes:
    - ./trickster.toml:/etc/trickster/trickster.conf:ro
  probe:
    image: alpine
    command:
    - /bin/sh
    - -c
    - |
      apk add --update curl
      while : ; do
        now=`date +%s`
        echo curl -sf "http://trickster:8000/api/v1/query_range?query=prometheus_http_request_duration_seconds_bucket&start=$$((now - 60))&end=$$now&step=15"
        curl -sf "http://trickster:8000/api/v1/query_range?query=prometheus_http_request_duration_seconds_bucket&start=$$((now - 60))&end=$$now&step=15" >/dev/null
        sleep 1
      done
```

trickster.toml
```toml
[main]
instance_id = 1

[proxy_server]
listen_port = 8000

[caches]
  [caches.default]
  type = 'memory'
  compression = true

    [caches.default.index]
    reap_interval_secs = 3
    flush_interval_secs = 5
    max_size_bytes = 536870912
    max_size_backoff_bytes = 16777216
    max_size_objects = 0
    max_size_backoff_objects = 100

[origins]
  [origins.default]
  type = 'prometheus'
  scheme = 'http'
  host = 'prometheus:9090'
  cache_name = 'default'
  timeout_secs = 30

[metrics]
listen_port = 8001

[logging]
log_level = 'debug'
```

### Result
```
# HELP trickster_proxy_request_duration_seconds Time required in seconds to proxy a given Prometheus query.
# TYPE trickster_proxy_request_duration_seconds histogram
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="none",le="0.05"} 23
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="none",le="0.1"} 23
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="none",le="0.5"} 23
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="none",le="1"} 23
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="none",le="5"} 23
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="none",le="10"} 23
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="none",le="20"} 23
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="none",le="+Inf"} 23
trickster_proxy_request_duration_seconds_sum{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="none"} 0.14030239999999997
trickster_proxy_request_duration_seconds_count{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="none"} 23
# HELP trickster_proxy_requests_total Count of downstream client requests handled by Trickster
# TYPE trickster_proxy_requests_total counter
trickster_proxy_requests_total{cache_status="none",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range"} 23
```

it don't cache anything.
