### ISSUE TITLE
Add endpoint for liveness probe

### ISSUE THREAD

**Issue by FUSAKLA** [Comcast/trickster#77]
I'm running Trickster in Kubernetes and when putting it in front of one Prometheus all is working just fine.

But now I tried putting it in front of the Thanos query layer and I'm experiencing regular restarts of the Trickster pods caused by failing liveness probe from Kubernetes.

I use the same configuration as helm chart
```yaml
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
```

The issue is that liveness probe should not test functionality of other components (Prometheus in this case) and just check if the app itself is ok. 

My issue is caused by high `/health` endpoint latency, so I suggest to add simple `/liveness` endpoint or something like that returning just HTTP status 200 so we know the web server is able to serve requests.
